### ISSUE TITLE
Enum serialization

### ISSUE THREAD

**Issue by bnayae** [barnardos-au/Neo4jMapper#17]
Can you recommend how to get  enum serialization work?

I'm using new the following code snippet:
```
 var params = Neo4jParameters().WithEntities<Foo>("foos", items);
```
Where Foo is having a property of type enum.

When I try to run it:
```
RunAsync(cypher, params )
```
I got the following error:
"Cannot understand value with type MyEnum"

**Comment by neildobson-au** [comment]
Problem here is that an enum cannot be handled natively by the driver/db, so directly passing collection using `WithValue` won't work, and as your example above shows, `WithEntities` fails because internally it calls ServiceStack `ToObjectDictionary` which typically should receive an object containing public props, each of which would get serialized into a string dictionary. But as you're passing enums, ServiceStack is probably just passing the collection as-is.

Quick answer here is to do the conversion yourself using ServiceStack `ConvertTo`.

``` csharp
using System;
using System.Collections.Generic;
using Neo4j.Driver.V1;
using Neo4jMapper;
using ServiceStack;

namespace ConsoleApp1
{
    public enum Color
    {
        Red,
        Green,
        Blue,
        White,
        Cyan,
        Yellow,
        Magenta,
        Black,
    }

    internal static class Program
    {
        private static void Main()
        {
            var ozFlagColors = new List<Color>()
            {
                Color.Red,
                Color.White,
                Color.Blue
            };

            var parameters = new Neo4jParameters()
                .WithValue("colors", ozFlagColors.ConvertTo<IEnumerable<string>>());

            var query = $@"
                UNWIND $colors AS color
                RETURN color";

            using (var driver = GraphDatabase.Driver("bolt://localhost:7687"))
            {
                using (var session = driver.Session())
                {
                    var result = session.Run(query, parameters);
                    var items = result.Map<string>();
                    foreach (var item in items)
                    {
                        Console.WriteLine($"Color: {item}");
                    }
                }            
            }
            
            Console.WriteLine("Done!"); Console.ReadLine();
        }
    }
}
```

Perhaps Value Mapper could see enums and deal with by calling ConvertTo<> internally. I'll look into it.

**Comment by bnayae** [comment]
Thanks for the quick response.
My case is more complex because I'm using WithEntities, therefore ConvertTo is not applicable.
I assume that I'will have to contribute some object level serialization behavior to ServiceStack or map the DTO to Entity which represent the enum as string.

**Comment by neildobson-au** [comment]
You only want to use `WithEntities` but want to pass a range of objects collections, some are entity collections, some are enum collections etc? Why not just create a wrapper, say `WithValues` which inspects the incoming objects. If they are entities it passes through to `WithEntities`, otherwise if it finds enums, does conversions and calls `WithValue`. Otherwise just implement your own Neo4jParameters, which is just a string dictionary wrapper anyway.

**Comment by neildobson-au** [comment]
I think perhaps I've misunderstood your problem. In your first example, `Foo` is actually a DTO which among other things contains a prop which is an enum. And you want that enum to be converted to a string? Correct? If so, then indeed there's an issue dealing with the enum because `ToObjectDictionary` does not know your value needs converting to a string.

In our applications we have service models (or DTOs) and entity models. We map from our DTOs to the entities before persistence. The DTOs contain emums and other complex types, and the entities mostly contain strings and value types. Here's how we do the mapping:

``` csharp
AutoMapping.RegisterConverter((CreatePerson from) =>
{
  var to = from.ConvertTo<PersonEntity>(true);
  to.DateOfBirth = from.DateOfBirth?.ToNeo4JClientDateTimeFormat();
  to.Ethnicities = from.Ethnicities.Select(e => new EthnicityEntity { Name = e }).ToList();
  to.AKAs = from.Akas.Select(a => new AlsoKnownAsEntity { Name = a }).ToList();
  to.EmailAddresses = from.EmailAddresses.Select(p => p.ConvertTo<EmailAddressEntity>()).ToList();
  to.PhoneNumbers = from.PhoneNumbers.Select(p => p.ConvertTo<PhoneNumberEntity>()).ToList();
  return to;
});

```

In this example `CreatePerson` is our DTO and contains complex types. Person entity matches the db model.

The first line using `ConvertTo` deals with property matches and handles enums etc. Note `DateOfBirth` is a string prop. We have a lot of data that was created using Neo4jClient. Its date field is in a proprietary format. So when we create or edit data we need to maintain backwards compatibility. So when we persist we convert the DateTime to a string using the Neo4jClient date/time format `yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK`.

For now I'd recommend using entity models.

**Comment by bnayae** [comment]
I assume that I will have to follow the same pattern of mapping the models to entities.
Thanks for the response.

**Comment by neildobson-au** [comment]
Just a heads up, I've updated Neo4jMapper to support Neo4jDriver v4. In addition I've pulled out the `ToParameterMap` from ServiceStack and implemented a custom converter to support among other things, serializing enums. Still WIP and I need to clean-up the code, but here's a working test:

https://github.com/neildobson-au/Neo4jMapper/commit/716cd388bce844059462b858b8dafe9a04df5ec7

**Comment by neildobson-au** [comment]
@bnayae You may have targeted the wrong method `ToObjectDictionary` is found in `ServiceStack.Text` package. The one in your PR is from the full `ServiceStack` package, which is not used in Neo4jMapper.

Also, to have chance of a successful PR to ServiceStack, you'll probably need to include a test.
