### ISSUE TITLE
Source code for Neo4jMapper.Core

### ISSUE THREAD

**Issue by bnayae** [barnardos-au/Neo4jMapper#27]
What is the repo of Neo4jMapper.Core?

**Comment by neildobson-au** [comment]
https://github.com/barnardos-au/Neo4jMapper/tree/master/src/Neo4jMapper.Core
https://github.com/barnardos-au/Neo4jMapper/tree/master/src/Neo4jMapper

The code for Neo4jMapper & Neo4jMapper.Core is the same. The only difference is the dependencies. Due to issues with differences in NETfx & Net Core APIs the two projects use different `ServiceStack.Text` packages

**Comment by neildobson-au** [comment]
See https://docs.servicestack.net/netcore#run-aspnet-core-apps-on-the-net-framework for more info
