### ISSUE TITLE
Please ship a .NET Core version!

### ISSUE THREAD

**Issue by pvillads** [barnardos-au/Neo4jMapper#29]
Guys,

I like your tool; it is just what I need. However, my WPF application leveraging Neo4j is entirely in .NET Core, for many good reasons. When I add your nuget package I get the error that it is restored using .NET framework 4.6.1... instead of .NETCoreApp. Also the dependency with the dependent packages are not satisfield.

I could use the source code and compile it myself, but I will not distribute other people's code on my github site, and I want to benefit from new versions that you may ship in the future.

Are there any plans for shipping a .NET Core version (or .NET 5) soon?

**Comment by neildobson-au** [comment]
Which nuget package are you referencing? There's 4 variants https://www.nuget.org/packages?q=neo4jmapper due to including signed / unsigned Neo4j.Driver packages and also due to anomalies with ServiceStack packages https://docs.servicestack.net/templates-corefx#reference-core-packages

I'd recommend you go with https://www.nuget.org/packages/Neo4jMapper.Core/

**Comment by neildobson-au** [comment]
Bear in mind, if you're already referencing any ServiceStack packages then you'll need to align them all to same version, and the .Core variants.
